-- Généré automatiquement depuis lib/activities.ts — ne pas éditer à la main.
-- 223 activités.
insert into activities (type, title, prompt, category, depth_level, duration_seconds, options, tags, active)
values
('open_question', 'Petit plaisir', 'Quel petit plaisir améliore toujours ta journée ?', 'leger', 1, null, null, '["quotidien"]'::jsonb, true),
('open_question', 'Réveil', 'Es-tu plutôt du matin ou plutôt du soir ?', 'leger', 1, null, null, '[]'::jsonb, true),
('open_question', 'Boisson', 'Quelle est la première boisson que tu prends le matin ?', 'leger', 1, null, null, '[]'::jsonb, true),
('secret_choice', 'Sucré ou salé', 'Au petit-déjeuner, tu choisis quoi ?', 'leger', 1, null, '["Sucré","Salé"]'::jsonb, '[]'::jsonb, true),
('secret_choice', 'Mer ou montagne', 'Pour des vacances, tu préfères…', 'leger', 1, null, '["La mer","La montagne"]'::jsonb, '[]'::jsonb, true),
('secret_choice', 'Chat ou chien', 'Team…', 'leger', 1, null, '["Chat","Chien"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Coup de tête', 'Qui de vous deux réserverait un voyage sur un coup de tête ?', 'drole', 1, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'En retard', 'Qui de vous deux arrive le plus souvent en retard ?', 'drole', 1, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Playlist', 'Qui de vous deux a la playlist la plus étrange ?', 'drole', 1, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Chef cuisine', 'Qui de vous deux cuisine le mieux ?', 'drole', 1, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('guess_my_answer', 'Pays de rêve', 'Quel pays l''autre rêve-t-il de visiter ?', 'voyages', 1, null, null, '[]'::jsonb, true),
('guess_my_answer', 'Dessert préféré', 'Quel est le dessert préféré de l''autre, à ton avis ?', 'leger', 1, null, null, '[]'::jsonb, true),
('estimation', 'Paris–New York', 'Combien de kilomètres séparent Paris de New York ?', 'leger', 1, null, null, '["distance"]'::jsonb, true),
('estimation', 'Cafés par jour', 'Combien de cafés un adulte français boit-il en moyenne par jour ?', 'drole', 1, null, null, '[]'::jsonb, true),
('complete_sentence', 'Week-end parfait', 'Un week-end parfait pour moi commence par…', 'leger', 1, null, null, '[]'::jsonb, true),
('complete_sentence', 'Rire garanti', 'Ce qui me fait toujours rire, c''est…', 'drole', 1, null, null, '[]'::jsonb, true),
('mission', 'Points communs', 'Trouvez trois choses que vous avez en commun.', 'leger', 1, 60, null, '["chrono"]'::jsonb, true),
('open_question', 'Talent caché', 'Quel est ton petit talent inutile mais amusant ?', 'drole', 1, null, null, '[]'::jsonb, true),
('open_question', 'Chanson du moment', 'Quelle chanson as-tu écoutée en boucle récemment ?', 'leger', 1, null, null, '[]'::jsonb, true),
('secret_choice', 'Super-pouvoir', 'Tu préfères pouvoir…', 'drole', 1, null, '["Voler","Être invisible"]'::jsonb, '[]'::jsonb, true),
('secret_choice', 'Thé ou café', 'Ta boisson chaude, c''est…', 'leger', 1, null, '["Thé","Café"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Photos', 'Qui de vous deux prend le plus de photos ?', 'leger', 1, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('guess_my_answer', 'Série récente', 'Quelle série l''autre a-t-il regardée en dernier ?', 'drole', 1, null, null, '[]'::jsonb, true),
('estimation', 'Pays du monde', 'Combien de pays y a-t-il dans le monde environ ?', 'voyages', 1, null, null, '[]'::jsonb, true),
('complete_sentence', 'Journée idéale', 'Ma journée idéale se termine par…', 'leger', 1, null, null, '[]'::jsonb, true),
('open_question', 'Saison préférée', 'Quelle est ta saison préférée et pourquoi ?', 'leger', 1, null, null, '[]'::jsonb, true),
('mission', 'Fous rires', 'Racontez chacun un souvenir qui vous fait encore rire.', 'drole', 1, 90, null, '["chrono"]'::jsonb, true),
('secret_choice', 'Ville ou campagne', 'Pour vivre, tu choisis…', 'leger', 1, null, '["La ville","La campagne"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Karaoké', 'Qui de vous deux se lancerait au karaoké en premier ?', 'drole', 1, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('open_question', 'Voyage marquant', 'Quel voyage t''a le plus marqué et pourquoi ?', 'voyages', 2, null, null, '[]'::jsonb, true),
('open_question', 'Recharge', 'Comment recharges-tu tes batteries après une semaine chargée ?', 'personnalite', 2, null, null, '[]'::jsonb, true),
('open_question', 'Enfance', 'Quel souvenir d''enfance te fait encore sourire ?', 'souvenirs', 2, null, null, '[]'::jsonb, true),
('secret_choice', 'Stable ou aventure', 'Préférerais-tu une vie très stable ou une vie pleine d''aventures ?', 'personnalite', 2, null, '["Vie stable","Vie d''aventures"]'::jsonb, '[]'::jsonb, true),
('secret_choice', 'Planifier ou improviser', 'Face à un week-end libre, tu préfères…', 'personnalite', 2, null, '["Tout planifier","Improviser"]'::jsonb, '[]'::jsonb, true),
('secret_choice', 'Solo ou groupe', 'Tu te ressources plutôt…', 'valeurs', 2, null, '["Seul·e","Entouré·e"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Décideur', 'Qui de vous deux prend les décisions le plus vite ?', 'personnalite', 2, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Organisateur', 'Qui de vous deux organiserait le mieux un voyage ?', 'voyages', 2, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Optimiste', 'Qui de vous deux voit le verre à moitié plein ?', 'personnalite', 2, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('guess_my_answer', 'Idéal détente', 'Quelle est l''activité détente préférée de l''autre ?', 'personnalite', 2, null, null, '[]'::jsonb, true),
('guess_my_answer', 'Prochaine destination', 'Où l''autre partirait-il demain si c''était gratuit ?', 'voyages', 2, null, null, '[]'::jsonb, true),
('guess_my_answer', 'Meilleure année', 'Quelle a été la meilleure année de l''autre, selon toi ?', 'souvenirs', 2, null, null, '[]'::jsonb, true),
('ranking', 'Ce qui compte', 'Classe ces valeurs selon leur importance pour toi.', 'valeurs', 2, null, '["Liberté","Stabilité","Amour","Réussite","Aventure"]'::jsonb, '[]'::jsonb, true),
('complete_sentence', 'Je suis à l''aise', 'Je me sens vraiment à l''aise quand…', 'personnalite', 2, null, null, '[]'::jsonb, true),
('complete_sentence', 'Si j''osais', 'Si j''osais davantage, je…', 'reves', 2, null, null, '[]'::jsonb, true),
('mission', 'Trois lieux', 'Nommez chacun trois lieux qui ont compté pour vous.', 'souvenirs', 2, 90, null, '["chrono"]'::jsonb, true),
('estimation', 'Tour Eiffel', 'En quelle année la Tour Eiffel a-t-elle été inaugurée ?', 'voyages', 2, null, null, '[]'::jsonb, true),
('estimation', 'Heures de sommeil', 'Combien d''heures dort en moyenne un adulte par nuit ?', 'personnalite', 2, null, null, '[]'::jsonb, true),
('open_question', 'Culture', 'Quelle culture ou pays aimerais-tu mieux comprendre ?', 'voyages', 2, null, null, '[]'::jsonb, true),
('open_question', 'Fierté récente', 'De quoi es-tu fier·e récemment, même d''une petite chose ?', 'personnalite', 2, null, null, '[]'::jsonb, true),
('secret_choice', 'Livre ou film', 'Pour une soirée calme, tu choisis…', 'personnalite', 2, null, '["Un livre","Un film"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Nostalgique', 'Qui de vous deux est le plus nostalgique ?', 'souvenirs', 2, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('guess_my_answer', 'Petit bonheur', 'Quel petit bonheur rend l''autre heureux à coup sûr ?', 'personnalite', 2, null, null, '[]'::jsonb, true),
('ranking', 'Priorités semaine', 'Classe ces valeurs comme tu les vis cette semaine.', 'personnalite', 2, null, '["Liberté","Stabilité","Amour","Réussite","Aventure"]'::jsonb, '[]'::jsonb, true),
('complete_sentence', 'En voyage', 'En voyage, je ne peux pas me passer de…', 'voyages', 2, null, null, '[]'::jsonb, true),
('mission', 'Points communs cachés', 'Trouvez un point commun surprenant que vous ignoriez.', 'personnalite', 2, 60, null, '["chrono"]'::jsonb, true),
('open_question', 'Odeur', 'Quelle odeur te ramène instantanément à un souvenir ?', 'souvenirs', 2, null, null, '[]'::jsonb, true),
('secret_choice', 'Grand ou petit', 'Tes rêves ressemblent plutôt à…', 'reves', 2, null, '["Un grand projet unique","Plein de petits projets"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Curieux', 'Qui de vous deux pose le plus de questions ?', 'personnalite', 2, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('guess_my_answer', 'Souvenir marquant', 'Quel souvenir l''autre citerait comme marquant ?', 'souvenirs', 2, null, null, '[]'::jsonb, true),
('open_question', 'Amitié durable', 'Qu''est-ce qui rend une amitié durable selon toi ?', 'relations', 3, null, null, '[]'::jsonb, true),
('open_question', 'Non négociable', 'Quelle est une valeur non négociable pour toi ?', 'valeurs', 3, null, null, '[]'::jsonb, true),
('open_question', 'Évolution', 'En quoi as-tu le plus changé ces dernières années ?', 'personnalite', 3, null, null, '[]'::jsonb, true),
('secret_choice', 'Cœur ou raison', 'Pour les grandes décisions, tu écoutes surtout…', 'valeurs', 3, null, '["Ton cœur","Ta raison"]'::jsonb, '[]'::jsonb, true),
('secret_choice', 'Parler ou écouter', 'Dans une relation, tu es plutôt…', 'relations', 3, null, '["Celui qui parle","Celui qui écoute"]'::jsonb, '[]'::jsonb, true),
('secret_choice', 'Réussite', 'La réussite, c''est d''abord…', 'valeurs', 3, null, '["Être serein","Accomplir de grandes choses"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Réconciliation', 'Qui de vous deux fait le premier pas après un désaccord ?', 'relations', 3, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Émotions', 'Qui de vous deux exprime le plus facilement ses émotions ?', 'personnalite', 3, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('guess_my_answer', 'Fierté profonde', 'De quoi l''autre est-il le plus fier dans sa vie ?', 'valeurs', 3, null, null, '[]'::jsonb, true),
('guess_my_answer', 'Qualité aimée', 'Quelle qualité l''autre valorise-t-il le plus chez ses proches ?', 'relations', 3, null, null, '[]'::jsonb, true),
('ranking', 'Vraies priorités', 'Classe ces valeurs telles qu''elles guident vraiment tes choix.', 'valeurs', 3, null, '["Liberté","Stabilité","Amour","Réussite","Aventure"]'::jsonb, '[]'::jsonb, true),
('complete_sentence', 'Je me sens libre', 'Je me sens vraiment libre quand…', 'personnalite', 3, null, null, '[]'::jsonb, true),
('complete_sentence', 'Confiance', 'Je fais confiance à quelqu''un quand…', 'relations', 3, null, null, '[]'::jsonb, true),
('complete_sentence', 'Ce qui me tient', 'Ce qui me tient debout dans les moments durs, c''est…', 'valeurs', 3, null, null, '[]'::jsonb, true),
('mission', 'Gratitude', 'Dites-vous chacun une chose que vous appréciez chez l''autre.', 'relations', 3, 60, null, '["chrono"]'::jsonb, true),
('open_question', 'Rêve mis de côté', 'Quel rêve as-tu mis de côté et aimerais raviver ?', 'reves', 3, null, null, '[]'::jsonb, true),
('open_question', 'Peur douce', 'Quelle petite peur aimerais-tu dépasser ?', 'personnalite', 3, null, null, '[]'::jsonb, true),
('secret_choice', 'Impact ou liberté', 'Tu rêves surtout de…', 'reves', 3, null, '["Avoir un impact","Être totalement libre"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Idéaliste', 'Qui de vous deux est le plus idéaliste ?', 'valeurs', 3, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('guess_my_answer', 'Vie idéale', 'À quoi ressemble la vie idéale de l''autre dans 5 ans ?', 'reves', 3, null, null, '[]'::jsonb, true),
('ranking', 'Ce qui te porte', 'Classe ces valeurs selon ce qui te porte vers l''avenir.', 'reves', 3, null, '["Liberté","Stabilité","Amour","Réussite","Aventure"]'::jsonb, '[]'::jsonb, true),
('complete_sentence', 'Un jour', 'Un jour, j''aimerais vraiment…', 'reves', 3, null, null, '[]'::jsonb, true),
('mission', 'Moment fondateur', 'Partagez chacun un moment qui vous a façonné.', 'souvenirs', 3, 120, null, '["chrono"]'::jsonb, true),
('open_question', 'Soutien', 'Comment aimes-tu être soutenu quand ça ne va pas ?', 'relations', 3, null, null, '[]'::jsonb, true),
('secret_choice', 'Changer ou accepter', 'Face à un défaut, tu préfères…', 'personnalite', 3, null, '["Le travailler","L''accepter"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Attentionné', 'Qui de vous deux pense le plus aux petites attentions ?', 'relations', 3, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('guess_my_answer', 'Recharge secrète', 'Qu''est-ce qui redonne vraiment de l''énergie à l''autre ?', 'personnalite', 3, null, null, '[]'::jsonb, true),
('open_question', 'Sens', 'Qu''est-ce qui donne du sens à ta vie en ce moment ?', 'profond', 4, null, null, '[]'::jsonb, true),
('open_question', 'Leçon', 'Quelle leçon importante la vie t''a-t-elle apprise ?', 'profond', 4, null, null, '[]'::jsonb, true),
('open_question', 'Version future', 'Que dirais-tu à la personne que tu seras dans dix ans ?', 'profond', 4, null, null, '[]'::jsonb, true),
('secret_choice', 'Regret ou peur', 'Ce qui te freine le plus, c''est plutôt…', 'profond', 4, null, '["La peur de l''échec","La peur de regretter"]'::jsonb, '[]'::jsonb, true),
('secret_choice', 'Traces', 'Tu aimerais laisser surtout…', 'profond', 4, null, '["Des souvenirs","Un impact durable"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Introspectif', 'Qui de vous deux réfléchit le plus au sens des choses ?', 'profond', 4, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('guess_my_answer', 'Ce qui compte', 'Qu''est-ce qui compte le plus pour l''autre, au fond ?', 'profond', 4, null, null, '[]'::jsonb, true),
('complete_sentence', 'Au fond de moi', 'Au fond de moi, j''ai besoin de…', 'profond', 4, null, null, '[]'::jsonb, true),
('complete_sentence', 'Fier de devenir', 'La personne que je deviens me rend fier·e parce que…', 'profond', 4, null, null, '[]'::jsonb, true),
('complete_sentence', 'Ce que je cherche', 'Ce que je cherche vraiment dans la vie, c''est…', 'profond', 4, null, null, '[]'::jsonb, true),
('mission', 'Reconnaissance', 'Dites-vous chacun ce que cette conversation vous a appris.', 'profond', 4, 90, null, '["chrono"]'::jsonb, true),
('open_question', 'Bonheur', 'C''est quoi, une vie réussie, pour toi ?', 'profond', 4, null, null, '[]'::jsonb, true),
('open_question', 'Vulnérabilité', 'Quand t''es-tu senti·e le plus vivant·e récemment ?', 'profond', 4, null, null, '[]'::jsonb, true),
('secret_choice', 'Temps ou sécurité', 'Si tu devais choisir…', 'profond', 4, null, '["Plus de temps libre","Plus de sécurité"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Courageux', 'Qui de vous deux a fait le choix le plus courageux ?', 'profond', 4, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('guess_my_answer', 'Rêve secret', 'Quel rêve l''autre n''ose presque jamais dire à voix haute ?', 'profond', 4, null, null, '[]'::jsonb, true),
('ranking', 'Au fond', 'Classe ces valeurs telles qu''elles comptent au plus profond.', 'profond', 4, null, '["Liberté","Stabilité","Amour","Réussite","Aventure"]'::jsonb, '[]'::jsonb, true),
('complete_sentence', 'Être aimé', 'Je me sens vraiment aimé·e quand…', 'relations', 4, null, null, '[]'::jsonb, true),
('mission', 'Un souhait', 'Formulez chacun un souhait sincère pour l''autre.', 'profond', 4, 60, null, '["chrono"]'::jsonb, true),
('open_question', 'Pardon', 'Qu''as-tu appris à te pardonner ?', 'profond', 4, null, null, '[]'::jsonb, true),
('secret_choice', 'Racines ou ailes', 'Tu as le plus besoin de…', 'profond', 4, null, '["Racines","Ailes"]'::jsonb, '[]'::jsonb, true),
('guess_my_answer', 'Plus grande force', 'Quelle est la plus grande force de l''autre, selon toi ?', 'profond', 4, null, null, '[]'::jsonb, true),
('open_question', 'Objet inutile', 'Quel objet inutile possèdes-tu et adores-tu ?', 'drole', 1, null, null, '[]'::jsonb, true),
('secret_choice', 'Pizza ou burger', 'Repas plaisir, tu choisis…', 'drole', 1, null, '["Pizza","Burger"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Dormeur', 'Qui de vous deux pourrait dormir n''importe où ?', 'leger', 1, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('estimation', 'Émojis', 'Combien d''émojis existe-t-il environ dans le clavier standard ?', 'drole', 1, null, null, '[]'::jsonb, true),
('complete_sentence', 'Bonne humeur', 'Rien ne me met de meilleure humeur que…', 'drole', 1, null, null, '[]'::jsonb, true),
('open_question', 'Ville coup de cœur', 'Quelle ville t''a donné envie d''y rester pour toujours ?', 'voyages', 2, null, null, '[]'::jsonb, true),
('guess_my_answer', 'Plat réconfort', 'Quel plat réconforte l''autre à tous les coups ?', 'leger', 1, null, null, '[]'::jsonb, true),
('secret_choice', 'Road trip ou farniente', 'Type de vacances idéal…', 'voyages', 2, null, '["Road trip","Farniente"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Aventurier', 'Qui de vous deux testerait la nourriture la plus étrange en voyage ?', 'voyages', 2, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('complete_sentence', 'Ça me manque', 'Une chose de mon passé qui me manque, c''est…', 'souvenirs', 2, null, null, '[]'::jsonb, true),
('open_question', 'Compliment', 'Quel compliment te touche le plus ?', 'personnalite', 2, null, null, '[]'::jsonb, true),
('secret_choice', 'Donner ou recevoir', 'Tu es plus à l''aise pour…', 'valeurs', 2, null, '["Donner","Recevoir"]'::jsonb, '[]'::jsonb, true),
('estimation', 'Battements de cœur', 'Combien de fois le cœur bat-il en moyenne par minute au repos ?', 'leger', 2, null, null, '[]'::jsonb, true),
('mission', 'Imitations', 'Décrivez chacun votre journée d''hier en une seule phrase drôle.', 'drole', 1, 45, null, '["chrono"]'::jsonb, true),
('open_question', 'Talent rêvé', 'Quel talent aimerais-tu maîtriser d''un claquement de doigts ?', 'reves', 2, null, null, '[]'::jsonb, true),
('who_of_us', 'Séries', 'Qui de vous deux enchaîne le plus d''épisodes d''affilée ?', 'drole', 1, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('guess_my_answer', 'Souvenir de voyage', 'Quel voyage l''autre garde-t-il en meilleur souvenir ?', 'voyages', 2, null, null, '[]'::jsonb, true),
('complete_sentence', 'Petit rituel', 'Mon petit rituel qui me fait du bien, c''est…', 'personnalite', 2, null, null, '[]'::jsonb, true),
('secret_choice', 'Ville ou nature', 'Ta vie idéale se déroule plutôt…', 'reves', 2, null, '["En pleine ville","En pleine nature"]'::jsonb, '[]'::jsonb, true),
('open_question', 'Belle rencontre', 'Quelle rencontre a changé quelque chose pour toi ?', 'relations', 3, null, null, '[]'::jsonb, true),
('guess_my_answer', 'Langage d''amour', 'Comment l''autre préfère-t-il recevoir de l''affection ?', 'relations', 3, null, null, '[]'::jsonb, true),
('secret_choice', 'Proche ou large', 'Tu préfères…', 'relations', 3, null, '["Peu d''amis très proches","Beaucoup de relations"]'::jsonb, '[]'::jsonb, true),
('complete_sentence', 'Je refuse', 'Je ne suis jamais prêt·e à sacrifier…', 'valeurs', 3, null, null, '[]'::jsonb, true),
('who_of_us', 'Sage', 'Qui de vous deux donne les meilleurs conseils ?', 'profond', 4, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('open_question', 'Première fois', 'Raconte une première fois dont tu es fier·e.', 'souvenirs', 2, null, null, '[]'::jsonb, true),
('estimation', 'Langues', 'Combien de langues parle-t-on environ dans le monde ?', 'voyages', 2, null, null, '[]'::jsonb, true),
('secret_choice', 'Routine ou nouveauté', 'Tu te sens mieux avec…', 'personnalite', 2, null, '["Une routine rassurante","De la nouveauté"]'::jsonb, '[]'::jsonb, true),
('complete_sentence', 'Si le temps', 'Si j''avais tout le temps du monde, je…', 'reves', 3, null, null, '[]'::jsonb, true),
('open_question', 'Mauvais goût', 'Quel plaisir coupable assumes-tu totalement ?', 'drole', 1, null, null, '[]'::jsonb, true),
('guess_my_answer', 'Trait dominant', 'Quel trait de caractère décrit le mieux l''autre ?', 'personnalite', 2, null, null, '[]'::jsonb, true),
('mission', 'Merci', 'Remerciez-vous chacun pour une qualité précise de l''autre.', 'valeurs', 3, 60, null, '["chrono"]'::jsonb, true),
('open_question', 'Héritage', 'Qu''aimerais-tu transmettre aux personnes que tu aimes ?', 'profond', 4, null, null, '[]'::jsonb, true),
('secret_choice', 'Comprendre ou ressentir', 'Face au monde, tu cherches surtout à…', 'profond', 4, null, '["Le comprendre","Le ressentir"]'::jsonb, '[]'::jsonb, true),
('complete_sentence', 'Ma paix', 'Je trouve la paix quand…', 'profond', 4, null, null, '[]'::jsonb, true),
('open_question', 'Réconfort', 'Quel plat te réconforte à tous les coups ?', 'leger', 1, null, null, '[]'::jsonb, true),
('open_question', 'Petit luxe', 'C''est quoi, ton petit luxe du quotidien ?', 'leger', 1, null, null, '[]'::jsonb, true),
('secret_choice', 'Douche', 'Douche plutôt…', 'leger', 1, null, '["Le matin","Le soir"]'::jsonb, '[]'::jsonb, true),
('secret_choice', 'Sonnerie', 'Le réveil, tu es plutôt…', 'leger', 1, null, '["Première sonnerie","Snooze x5"]'::jsonb, '[]'::jsonb, true),
('secret_choice', 'Pizza', 'La pizza à l''ananas, c''est…', 'leger', 1, null, '["Oui, assume","Non, jamais"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Ranger', 'Qui de vous deux est le plus ordonné ?', 'leger', 1, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Perdu', 'Qui de vous deux se perd le plus facilement ?', 'leger', 1, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('complete_sentence', 'Le matin', 'Ma journée démarre bien quand…', 'leger', 1, null, null, '[]'::jsonb, true),
('estimation', 'Sommeil idéal', 'Selon toi, combien d''heures de sommeil sont idéales par nuit ?', 'leger', 1, null, null, '[]'::jsonb, true),
('open_question', 'Guilty pleasure', 'Quelle émission ou musique tu adores en cachette ?', 'leger', 1, null, null, '[]'::jsonb, true),
('open_question', 'Surnom gênant', 'Quel surnom ridicule on t''a déjà donné ?', 'drole', 1, null, null, '[]'::jsonb, true),
('open_question', 'Honte', 'Raconte un moment gênant dont tu ris aujourd''hui.', 'drole', 1, null, null, '[]'::jsonb, true),
('who_of_us', 'Danse', 'Qui de vous deux se lâcherait le plus sur la piste ?', 'drole', 1, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Pleurer film', 'Qui de vous deux pleure devant les films ?', 'drole', 1, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Ronfler', 'Qui de vous deux ronflerait le plus fort ?', 'drole', 1, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('secret_choice', 'Zombie', 'Apocalypse zombie : tu es…', 'drole', 1, null, '["Le stratège","Le premier mangé"]'::jsonb, '[]'::jsonb, true),
('secret_choice', 'Talent', 'Ton super-pouvoir inutile idéal…', 'drole', 1, null, '["Parler aux pigeons","Plier la pizza par la pensée"]'::jsonb, '[]'::jsonb, true),
('complete_sentence', 'Panique', 'Je perds tous mes moyens quand…', 'drole', 1, null, null, '[]'::jsonb, true),
('complete_sentence', 'Fierté absurde', 'Je suis bizarrement fier·e de…', 'drole', 1, null, null, '[]'::jsonb, true),
('mission', 'Grimaces', 'Faites chacun votre pire grimace. L''autre note sur 10.', 'drole', 1, 30, null, '["chrono"]'::jsonb, true),
('mission', 'Accent', 'Racontez votre matinée avec un accent au choix.', 'drole', 1, 45, null, '["chrono"]'::jsonb, true),
('estimation', 'Selfies', 'Combien de selfies sont pris dans le monde chaque jour, à ton avis ? (millions)', 'drole', 1, null, null, '[]'::jsonb, true),
('open_question', 'Prochaine évasion', 'Si tu partais demain, ce serait où ?', 'voyages', 1, null, null, '[]'::jsonb, true),
('open_question', 'Coup de cœur', 'Quel endroit t''a coupé le souffle ?', 'voyages', 2, null, null, '[]'::jsonb, true),
('open_question', 'Voyage rêvé', 'Quel voyage tu n''as pas encore osé faire ?', 'voyages', 2, null, null, '[]'::jsonb, true),
('secret_choice', 'Bagage', 'En voyage, tu es plutôt…', 'voyages', 1, null, '["Valise minimaliste","J''emporte tout"]'::jsonb, '[]'::jsonb, true),
('secret_choice', 'Rythme', 'Ton voyage idéal…', 'voyages', 2, null, '["Tout voir, bouger","Se poser, savourer"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Guide', 'Qui de vous deux ferait le meilleur guide ?', 'voyages', 2, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('guess_my_answer', 'Destination secrète', 'Quel pays l''autre rêve de visiter en secret ?', 'voyages', 2, null, null, '[]'::jsonb, true),
('complete_sentence', 'L''ailleurs', 'Ce que je cherche en voyageant, c''est…', 'voyages', 2, null, null, '[]'::jsonb, true),
('open_question', 'Retour', 'Quel endroit te donne toujours envie d''y retourner ?', 'voyages', 2, null, null, '[]'::jsonb, true),
('estimation', 'Fuseaux', 'Combien de fuseaux horaires y a-t-il dans le monde ?', 'voyages', 2, null, null, '[]'::jsonb, true),
('open_question', 'Odeur d''enfance', 'Quelle odeur te ramène direct en enfance ?', 'souvenirs', 1, null, null, '[]'::jsonb, true),
('open_question', 'Chanson-madeleine', 'Quelle chanson te ramène à un moment précis ?', 'souvenirs', 2, null, null, '[]'::jsonb, true),
('open_question', 'Été d''avant', 'Décris un été qui t''a marqué.', 'souvenirs', 2, null, null, '[]'::jsonb, true),
('open_question', 'Première fierté', 'Quel est ton premier vrai souvenir de fierté ?', 'souvenirs', 2, null, null, '[]'::jsonb, true),
('secret_choice', 'Mémoire', 'Tu gardes surtout…', 'souvenirs', 2, null, '["Les images","Les émotions"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Archiviste', 'Qui de vous deux garde le plus de souvenirs (photos, objets) ?', 'souvenirs', 2, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('guess_my_answer', 'Belle année', 'Quelle a été la plus belle année de l''autre, à ton avis ?', 'souvenirs', 2, null, null, '[]'::jsonb, true),
('complete_sentence', 'Ça me manque', 'Une époque qui me manque, c''est…', 'souvenirs', 2, null, null, '[]'::jsonb, true),
('complete_sentence', 'Je n''oublierai jamais', 'Je n''oublierai jamais le jour où…', 'souvenirs', 3, null, null, '[]'::jsonb, true),
('mission', 'Trois madeleines', 'Nommez chacun trois souvenirs qui vous font sourire.', 'souvenirs', 2, 60, null, '["chrono"]'::jsonb, true),
('open_question', 'Énergie', 'Qu''est-ce qui te redonne de l''énergie à coup sûr ?', 'personnalite', 2, null, null, '[]'::jsonb, true),
('open_question', 'Agacement', 'Quel petit truc t''agace plus que de raison ?', 'personnalite', 2, null, null, '[]'::jsonb, true),
('open_question', 'Compliment juste', 'Quel compliment te touche vraiment ?', 'personnalite', 2, null, null, '[]'::jsonb, true),
('open_question', 'Évolution', 'Sur quoi as-tu le plus grandi ces dernières années ?', 'personnalite', 3, null, null, '[]'::jsonb, true),
('secret_choice', 'Recharge', 'Tu recharges tes batteries…', 'personnalite', 2, null, '["Seul·e au calme","Entouré·e"]'::jsonb, '[]'::jsonb, true),
('secret_choice', 'Décision', 'Tu décides plutôt avec…', 'personnalite', 2, null, '["La tête","Le ventre"]'::jsonb, '[]'::jsonb, true),
('secret_choice', 'Zone de confort', 'Face à l''inconnu, tu es plutôt…', 'personnalite', 3, null, '["Je fonce","J''observe d''abord"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Spontané', 'Qui de vous deux est le plus spontané ?', 'personnalite', 2, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Sensible', 'Qui de vous deux ressent les choses le plus fort ?', 'personnalite', 3, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('guess_my_answer', 'Recharge de l''autre', 'Qu''est-ce qui ressource vraiment l''autre ?', 'personnalite', 2, null, null, '[]'::jsonb, true),
('guess_my_answer', 'Petite peur', 'Quelle petite peur l''autre aimerait dépasser ?', 'personnalite', 3, null, null, '[]'::jsonb, true),
('complete_sentence', 'À l''aise', 'Je me sens pleinement moi-même quand…', 'personnalite', 2, null, null, '[]'::jsonb, true),
('complete_sentence', 'Ma force', 'Ma plus grande force, c''est sans doute…', 'personnalite', 3, null, null, '[]'::jsonb, true),
('ranking', 'Ce qui me porte', 'Classe ces valeurs selon ce qui te porte au quotidien.', 'personnalite', 2, null, '["Liberté","Stabilité","Amour","Réussite","Aventure"]'::jsonb, '[]'::jsonb, true),
('open_question', 'Non négociable', 'Quelle est ta valeur non négociable ?', 'valeurs', 3, null, null, '[]'::jsonb, true),
('open_question', 'Admiration', 'Quelle qualité admires-tu le plus chez quelqu''un ?', 'valeurs', 3, null, null, '[]'::jsonb, true),
('open_question', 'Réussir', 'Ça veut dire quoi, réussir sa vie, pour toi ?', 'valeurs', 3, null, null, '[]'::jsonb, true),
('who_of_us', 'Fidèle aux principes', 'Qui de vous deux tient le plus à ses principes ?', 'valeurs', 3, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('complete_sentence', 'Debout', 'Ce qui me tient debout, c''est…', 'valeurs', 3, null, null, '[]'::jsonb, true),
('ranking', 'Mes priorités', 'Classe ces valeurs telles qu''elles guident tes choix.', 'valeurs', 3, null, '["Liberté","Stabilité","Amour","Réussite","Aventure"]'::jsonb, '[]'::jsonb, true),
('open_question', 'Talent rêvé', 'Quel talent aimerais-tu avoir d''un claquement de doigts ?', 'reves', 2, null, null, '[]'::jsonb, true),
('open_question', 'Vie idéale', 'À quoi ressemblerait une vie qui te comble ?', 'reves', 3, null, null, '[]'::jsonb, true),
('secret_choice', 'Cap', 'Tu rêves plutôt de…', 'reves', 2, null, '["Un grand projet","Plein de petites joies"]'::jsonb, '[]'::jsonb, true),
('secret_choice', 'Empreinte', 'Tu aimerais surtout…', 'reves', 3, null, '["Vivre pleinement","Laisser une trace"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Rêveur', 'Qui de vous deux a les rêves les plus fous ?', 'reves', 3, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('guess_my_answer', 'Rêve tu', 'Quel rêve l''autre n''ose presque pas dire tout haut ?', 'reves', 3, null, null, '[]'::jsonb, true),
('complete_sentence', 'Si j''osais', 'Si je n''avais peur de rien, je…', 'reves', 3, null, null, '[]'::jsonb, true),
('mission', 'Trois envies', 'Partagez chacun trois choses à faire avant 5 ans.', 'reves', 3, 60, null, '["chrono"]'::jsonb, true),
('open_question', 'Amitié', 'Qu''est-ce qui rend une amitié précieuse pour toi ?', 'relations', 3, null, null, '[]'::jsonb, true),
('open_question', 'Être soutenu', 'Comment aimes-tu qu''on te soutienne quand ça va mal ?', 'relations', 3, null, null, '[]'::jsonb, true),
('open_question', 'Belle rencontre', 'Quelle rencontre a changé quelque chose en toi ?', 'relations', 3, null, null, '[]'::jsonb, true),
('secret_choice', 'Dispute', 'Après un désaccord, tu es plutôt…', 'relations', 3, null, '["Premier pas","J''ai besoin de temps"]'::jsonb, '[]'::jsonb, true),
('mission', 'Gratitude', 'Dites-vous chacun une chose sincère que vous appréciez chez l''autre.', 'relations', 3, 60, null, '["chrono"]'::jsonb, true),
('open_question', 'Leçon', 'Quelle leçon la vie t''a-t-elle apprise à la dure ?', 'profond', 4, null, null, '[]'::jsonb, true),
('open_question', 'Lettre', 'Que dirais-tu à toi-même il y a dix ans ?', 'profond', 4, null, null, '[]'::jsonb, true),
('secret_choice', 'Moteur', 'Ce qui te pousse le plus, c''est…', 'profond', 4, null, '["La peur de rater","L''envie de créer"]'::jsonb, '[]'::jsonb, true),
('who_of_us', 'Courage', 'Qui de vous deux a pris la décision la plus courageuse ?', 'profond', 4, null, '["Moi","L''autre"]'::jsonb, '[]'::jsonb, true),
('complete_sentence', 'Je cherche', 'Ce que je cherche vraiment, c''est…', 'profond', 4, null, null, '[]'::jsonb, true),
('open_question', 'Transmettre', 'Qu''aimerais-tu transmettre à ceux que tu aimes ?', 'profond', 4, null, null, '[]'::jsonb, true);
